version: "3.9"

services:
  optivest-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres-db
      - optivest-python

  postgres-db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${PGDATABASE:-optivest}
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}

  optivest-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: https://optivest-backend.up.railway.app

  optivest-python:
    build: ./python-service
    ports:
      - "5000:5000"
    environment:
      PORT: 5000